### ISSUE TITLE
Some users' sidebar button disappered when enter the server.

### ISSUE THREAD

**Issue by XeonKA** [GTNewHorizons/ServerUtilities#28]
Version: 2.0.8 in GTNH2.5.1 Thermal-Unofficial private server
Some users works well after reboot the game(or restart server),some is still have the issue.
Commands works well.
![QQ图片20240106165211](https://github.com/GTNewHorizons/ServerUtilities/assets/33470743/bd30d59a-ca71-480a-b153-dd35e198bee5)
![QQ图片20240106165713](https://github.com/GTNewHorizons/ServerUtilities/assets/33470743/f3678905-0783-439d-9c3d-c5bcb0d2939b)

**Comment by Lyfts** [comment]
Is this something that happens frequently or is it a one off?

If the players do /client_config can they still see the buttons in the sidebar button config menu?

**Comment by XeonKA** [comment]
> Is this something that happens frequently or is it a one off?
> 
Frequently,one player have this issue three times today.

> If the players do /client_config can they still see the buttons in the sidebar button config menu?
Yes they can.
![QQ图片20240106193729](https://github.com/GTNewHorizons/ServerUtilities/assets/33470743/e3f69cf3-8488-41c3-a883-62a255820bab)
![QQ图片20240106193743](https://github.com/GTNewHorizons/ServerUtilities/assets/33470743/6ea1afb1-0106-4cff-b2f1-7d5a4dc5153c)

**Comment by YannickMG** [comment]
I've seen this issue a few times as well, though I didn't catch the reproduction steps.

**Comment by Lyfts** [comment]
Just documenting this here in case someone stumbles upon this and can figure it out or give some insight.

The why this happens is because the client doesn't register that the server has serverutils loaded. 
The how is a mystery so far.
It's being sent the same map that other mods use to handle [mod rejections](https://github.com/GTNewHorizons/ServerUtilities/blob/3e92a955d949cd10ec731933b73fc3b94a8e4715/src/main/java/serverutils/ServerUtilities.java#L185-L189) which is then processed in [SidedUtils ](https://github.com/GTNewHorizons/ServerUtilities/blob/master/src/main/java/serverutils/lib/util/SidedUtils.java) first added to another map for safekeeping in `checkModLists()` that map is then checked if it contains the modId through `areAllModsLoadedOnServer()` and `isModLoadedOnServer()`. 
Seeing as the users aren't being disconnected due to other mod rejections it's safe to assume that the map is being sent correctly.

Most players never have this problem, some have it once and then a restart fixes it and others have it frequently and restarting doesn't seem to help them.

**Comment by XeonKA** [comment]
When I
enter server➡disable PC's network➡disconneted from server➡reopen network➡enter server,
the issue happen.
Afer reboot the game it works well.

**Comment by Lyfts** [comment]
@XeonKA try updating to https://github.com/GTNewHorizons/ServerUtilities/releases/tag/2.0.14

**Comment by XeonKA** [comment]
> @XeonKA try updating to https://github.com/GTNewHorizons/ServerUtilities/releases/tag/2.0.14

Fixed.

**Comment by XeonKA** [comment]
Um,sorry,sometimes I can reproduce this issue after updating to 2.0.14.
Client side log after connect error and rejoin the server:https://pastebin.ubuntu.com/p/JXmzk3kKJQ/
Seems nothing useful information in server logs.
I can confirm restart client can fix it.

**Comment by Lyfts** [comment]
Alright we're probably gonna have to do that check another way then...

But just to be sure, can you try turning on the config setting "print-more-info" and send a log with that next time the issue happens?

**Comment by XeonKA** [comment]
Client side log after connection error and issue happens,print-more-info set true.
https://pastebin.ubuntu.com/p/yqp9H52Wzw/
@Lyfts
